# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricaoEvento', '0003_auto_20171106_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='evento',
        ),
    ]
